VenusProtocol/governance-contracts

contracts/Governance/Timelock.sol
Adds natspec to the timelock contract
=> Add natspec to timelock

deploy/001-access-control.ts, deploy/helpers/constants.ts, deploy/helpers/deploymentUtils.ts
Refactors ACM deployment script to pull addresses from packages and support deploying to hardhat
=> Support hardhat deployments

contracts/legacy/GovernorBravoDelegateV1.sol, contracts/legacy/GovernorBravoInterfaces.sol
Adds GovernorBravo V1 contract to legacy contracts. 
The main difference with GovernorBravo V1 is that it has a single governance route
=> feat: add governor bravo v1 to legacy contracts

CHANGELOG.md, contracts/legacy/GovernorBravoDelegateV1.sol, contracts/legacy/GovernorBravoInterfaces.sol, deployments/bscmainnet/AccessControlManager.json, deployments/bsctestnet/AccessControlManager.json, package.json
Merges main back down into develop including version tags/ commits
=> Rebase main onto develop

deployments/bscmainnet.json, deployments/bsctestnet.json, package.json
Create a merge commit to bring down tags
=> Use merge strategy

deploy/002-access-control.ts, helpers/deploy/deploymentUtils.ts
=> fix: fix typescript errors

.github/workflows/ci.yml, hardhat.config.ts
Exclude external deployments when exporting to avoid clashing and polluting exports with external deployments
=> [VEN-2242]: exclude external deployments when exporting

.github/workflows/ci.yml, deployments/opbnbmainnet.json, deployments/opbnbmainnet_addresses.json, deployments/opbnbtestnet_addresses.json
=> [VEN-2191]: add opbnbtestnet and opbnbmainnet to the ci step to extract addresses

deployments/opbnbmainnet.json, deployments/opbnbmainnet_addresses.json
Export opbnb mainnet ACM deployments
=> Fix release 

contracts/Cross-chain/BaseOmnichainControllerDest.sol, contracts/Cross-chain/BaseOmnichainControllerSrc.sol, contracts/Cross-chain/OmnichainExecutorOwner.sol, contracts/Cross-chain/OmnichainGovernanceExecutor.sol, contracts/Cross-chain/OmnichainProposalSender.sol, contracts/Cross-chain/interfaces/IOmnichainGovernanceExecutor.sol, contracts/Cross-chain/interfaces/ITimelock.sol, contracts/Governance/TimelockV8.sol, tests/Cross-chain/Omnichain.ts, tests/Governance/GovernanceBravo/timelock.ts
=> [VEN-2339]: Certik audit fixes

deploy/001-timelock.ts
=> Add delay config for Arbitrum

contracts/Cross-chain/BaseOmnichainControllerDest.sol, contracts/Cross-chain/BaseOmnichainControllerSrc.sol, contracts/Cross-chain/OmnichainExecutorOwner.sol, contracts/Cross-chain/OmnichainGovernanceExecutor.sol, contracts/Cross-chain/OmnichainProposalSender.sol, contracts/Cross-chain/interfaces/IOmnichainGovernanceExecutor.sol, contracts/Cross-chain/interfaces/ITimelock.sol, contracts/Governance/TimelockV8.sol, tests/Cross-chain/Omnichain.ts
=> [VEN-2531]: fix Cantina findings

.github/workflows/ci.yml, deploy/000-lz-mocks.ts, deploy/003-omnichain-source.ts, deploy/004-omnichain-executor-remote.ts, deploy/005-remote-timelock.ts, deploy/006-omnichain-executorOwner-remote.ts, deployments/arbitrumone/.migrations.json, deployments/arbitrumsepolia/.migrations.json, deployments/ethereum/.migrations.json, deployments/opbnbmainnet/.migrations.json, deployments/opbnbtestnet/.migrations.json, deployments/sepolia/.migrations.json, deployments/zksyncsepolia/.migrations.json, helpers/deploy/constants.ts, helpers/deploy/deploymentUtils.ts, yarn.lock
Support mocked layerzero endpoint when deploying to hardhat
=> refactor: support layerzero endpoint mock on hardhat network

contracts/test/TestTimelockV8.sol, tests/Governance/GovernanceBravo/timelock.ts
Increase GRACE_PERIOD on test timelock to make testing easier
=> refactor: increase test timelock grace period

package.json, yarn.lock
=> chore: Update hardhat and smock dependencies

funding.json, yarn.lock
Verify repo for Atlas Optimism
=> chore: verify repo for Atlas Optimism

helpers/deploy/deploymentConfig.ts
=> chore: add support to unichain sepolia in the hardhat configuration

helpers/deploy/deploymentConfig.ts
=> chore: add unichain mainnet missing config

yarn.lock
=> Fix CI checks on develop

contracts/Governance/AccessControlledV8.sol, yarn.lock
Resolves #
This PR makes the _accessControlManager variable of AccessControlledV8 internal.
=> [VEN-2887]: make _accessControlManager variable internal
